homework 4
NadyaTukan/Utility_storage pull request #4
Opened 2023-11-21 16:26 UTC by NadyaTukan

2023-11-23 11:16 UTC, progressicu requested changes

2023-11-23 11:16 UTC, progressicu commented on src/main/java/org/example/repository/StorageUsefulMaterials.java
> +public class StorageUsefulMaterials {
Напишу сюда, т.к. в другие места гитхаб не позволяет. 

1. Ты в методе init() считываешь данные и наполняешь данный репозиторий. Но так немного неправильно в том плане, что данный класс отвечает только за работу с хранением, но не должен отвечать за наполнение самого себя из некоторого источника.

Лучше всего будет из этого метода сделать CommandLineRunner типа FillStorageUsefulMaterialsRunner, который как раз будет заполнять данный репозиторий через метод create или добавить ещё один при необходимости

2. По методу Long getNextId(). Делая этот метод публичным, ты грубо говоря надеяшься, что разработчик не забудет вызвать этот метод перед созданием объекта и сохранением его в репозитории. Но это неправильно. Лучше стоит его вызывать в самом репозитории в методу create. Тем самым ты упростишь работу с репозиторием и избежишь неконсистентных данных, в случае если кто-то забудет это вызвать
3. Определись с названиями. У тебя сущность - UsefulMaterial, репозиторий - StorageUsefulMaterials, сервис - StorageService, контроллер - StorageController, дто - *MaterialDto. Обычно всё должно крутиться вокруг названия сущности и просто в начале/конце добавляешь соответствующие части. Т.е. в твоём примере сервис должен быть UsefulMaterialService, репозиторий - UsefulMaterialRepository (можно и UsefulMaterialStorage, если больше нравится), ...

2023-11-23 11:16 UTC, progressicu commented on src/main/java/org/example/service/storade/StorageServiceImpl.java
>      @Autowired
Это аннотация необязательно в случае, когда спринг через конструктор внедряет бины. Так что для красоты кода давай уберем это

2023-11-23 11:16 UTC, progressicu commented on src/main/java/org/example/service/grade/argument/CreateGradeArgument.java
> +    @NotNull(message = "не указан ID записи")
1. Обычно валидация происходит на входе в микросервис. Т.е. в твоём случае на уровне дто они должны быть, а дальше мы считаем что все данные валидны, ну и только в некоторых случаях делаем проверки сложнее
2. А почему Create/Update-MaterialDto валидацию не повешала?

2023-11-23 11:16 UTC, progressicu commented on src/main/java/org/example/repository/StorageGrades.java
> +    public List<Grade> searchById(@NotBlank Long id) {
стоит конкретизировать, что поиск не по id оценки, а по id материала

2023-11-23 11:16 UTC, progressicu commented on src/main/java/org/example/api/grade/GradeController.java
> +    public List<GradeDto> searchByPartOfName(@RequestParam long idMatirial) {
ошибка в наименование параметра

2023-11-23 11:16 UTC, progressicu commented on src/main/java/org/example/action/grade/CreateGradeAction.java
> +        storageService.searchByID(argument.getIdUsefulMaterial());
сходу не понятно зачем ты это вызываешь. Лучше стоит добавить метод existsById

2023-11-23 11:16 UTC, progressicu commented on src/test/java/org/example/api/storage/StorageUsefulMaterialsControllerIT.java
>  @TestMethodOrder(MethodOrderer.OrderAnnotation.class)
Твои тесты должны быть независимы, т.к. иначе будут проблемы. Допустим я хочу запустить чисто второй тест (deleteDeleteIsOk), но в данном случае он упадёт, т.к. ожидаем, что сначала будем вызывать первый тест (postCreate).

Как сделать - в arrange или в beforeEach просто наполни нужными данными StorageUsefulMaterials и потом вызывай что нужно тебе

2023-11-26 11:27 UTC, NadyaTukan commented on src/main/java/org/example/repository/StorageUsefulMaterials.java
> +public class StorageUsefulMaterials {
подправила

2023-11-28 23:15 UTC, progressicu requested changes

2023-11-28 23:15 UTC, progressicu commented on src/main/java/org/example/action/grade/CreateGradeAction.java
> +    private void existsById(CreateGradeActionArgument argument) {
имел ввиду добавить метод в usefulMaterialService

2023-11-28 23:15 UTC, progressicu commented on src/main/java/org/example/action/grade/CreateGradeActionArgument.java
> +    @NotNull(message = "не указан id записи")
на уровне дто уже проверяется, так что с аргументов можно убрать

2023-11-28 23:15 UTC, progressicu commented on src/main/java/org/example/action/usefulMaterial/FillStorageUsefulMaterialsRunner.java
> +        create();
можно было и без create(), а сразу здесь вызвать usefulMaterialRepository.putAllInUsefulMaterials(Reader.read(pathToData));

2023-11-28 23:15 UTC, progressicu commented on src/main/java/org/example/repository/GradeRepository.java
> +        grades.put(grade.getId(), grade);
здесь же тоже надо было getNextId() вызывать, аналогичная ситуация же

2023-11-28 23:15 UTC, progressicu commented on src/main/java/org/example/repository/UsefulMaterialRepository.java
> +    public void putAllInUsefulMaterials(Map<Long, UsefulMaterial> newUsefulMaterials) {
можно было назвать просто putAll, итак понятно, что в UsefulMaterialRepository хранятся UsefulMaterials

2023-11-28 23:15 UTC, progressicu commented on src/test/java/org/example/api/usefulMaterial/UsefulMaterialRepositoryControllerIT.java
> +class UsefulMaterialRepositoryControllerIT {
1. просто UsefulMaterialControllerIT.
2. А где аналогичный тест на оценки?

2023-11-28 23:15 UTC, progressicu commented on src/test/java/org/example/api/usefulMaterial/UsefulMaterialRepositoryControllerIT.java
> +        UsefulMaterialDto material = mapper.toDto(usefulMaterialForPostCreate);
1. А зачем ты вообще вынесла usefulMaterialForPostCreate за пределы метода, если кроме этого места больше нигде не используешь. (аналогичное замечание про usefulMaterialForDeleteDelete, usefulMaterialForPostUpdateByID)
2. Для тестирования ты используешь рабочий код (я про маппер сейчас), но если в нём будет ошибка, то соответственно всё пойдет не так. Тесты должны быть максимально независимы от рабочего кода
3. Можно было просто сразу создать UsefulMaterialDto вместе  UsefulMaterial

2023-11-28 23:15 UTC, progressicu commented on src/test/java/org/example/api/usefulMaterial/UsefulMaterialRepositoryControllerIT.java
> +        CreateUsefulMaterialDto dto = new CreateUsefulMaterialDto(material.getName(),
ошибка в типе дто

2023-11-28 23:15 UTC, progressicu commented on src/test/java/org/example/api/usefulMaterial/UsefulMaterialRepositoryControllerIT.java
> +        UsefulMaterialDto responce = webTestClient.post()
response

2023-12-04 12:15 UTC, NadyaTukan commented on src/test/java/org/example/api/usefulMaterial/UsefulMaterialRepositoryControllerIT.java
> +        UsefulMaterialDto responce = webTestClient.post()
подправила

2023-12-11 12:06 UTC, progressicu commented on src/test/java/org/example/api/grade/GradeControllerIT.java
> +        assertions.assertThat(gradeRepository.searchByUsefulMaterialId(2L)).isEqualTo(null);
так ты же создавала оценку к 1L

2023-12-11 12:07 UTC, progressicu commented on src/test/java/org/example/api/grade/GradeControllerIT.java
> +    void deleteDeleteIsOk(SoftAssertions assertions) {
deleteDelete ?

2023-12-11 12:08 UTC, progressicu approved these changes

2023-12-26 09:39 UTC, merged